account:
  title: Curriculr
  locale: en
  time_zone: "Mountain Time (US & Canada)"
  theme: 
    name: bootstrap
    fluid: false
    flavor: vanilla
    logo: true
  
  use_gravatar: true

  require_admin_approval_of_classes: true
  require_admin_approval_of_blogs: true

  mailer:
    send_from: admin@example.com
    contact_us_at: admin@example.com
    noreply: noreply@example.com

  social_pages: 
    facebook: https://www.facebook.com/curriculr
    twitter: https://twitter.com/curriculr
    google-plus: https://plus.google.com/101434561769243560321
    youtube:
    linkedin:
    github:

  allow_user_student_dependents: false
  allow_file_uploads: true
  allowed_file_types:
    image:
      - png
      - jpg
      - jpeg
    video:
      - mp4
    audio:
      - mp3
    document:
      - pdf
    other:
      - txt
      - csv
      - dat