site:
  supported_locales:
    ar: العربية
    en: English

  default_account: main
  default_theme: sunshine

  ace_code_editor_style: tomorrow
  syntax_highlighter_style: colorful

  filter_classes_by:
    language: true
    level: true
    category: true

  file_content_types:
    pdf: application/pdf
    mp4: video/mp4
    mp3: audio/mpeg
    png: image/png
    jpg: image/jpeg
    jpeg: image/jpeg
    gif: image/gif
    csv: text/csv
    txt: text/plain
    dat: application/octet-stream
