site:
  supported_locales:
    ar: العربية
    en: English

  default_account: main

  sublimevideo_site_token: 
  ace_code_editor_style: tomorrow
  syntax_highlighter_style: colorful

  analytics:
    tracking_id: 'UA-11122233-3'
    domain: 'example.com'

  filter_classes_by:
    language: true
    level: true
    category: true
