account:
  title: Curriculr

  locale: en
  allow_locale_setting_in:
    url_param: false
    cookie: false
    session: false

  time_zone: "Mountain Time (US & Canada)"
  theme: sunshine

  use_gravatar: true

  require_admin_approval_of_classes: true
  require_admin_approval_of_blogs: true

  allow_banner_ads: false
  allow_user_student_dependents: false
  allow_file_uploads: true
  allowed_file_types:
    image:
      - png
      - jpg
      - jpeg
      - gif
    video:
      - mp4
    audio:
      - mp3
    document:
      - pdf
    other:
      - txt
      - csv
