site:
  supported_locales:
    ar: العربية
    en: English

  available_themes:
    bootstrap:
      parent:
      about: The default theme; based on Bootstrap 3.

  default_account: main

  ace_code_editor_style: tomorrow
  syntax_highlighter_style: colorful

  analytics:
    tracking_id: 'UA-11122233-3'
    domain: 'example.com'

  filter_classes_by:
    language: true
    level: true
    category: true
