account:
  title: Duroosi
  locale: en
  time_zone: "Mountain Time (US & Canada)"
  theme: 
    name: bootstrap
    fluid: false
    flavor: vanilla

  allow_file_upload: true
  allow_user_student_dependents: false
  use_gravatar: true

  require_admin_approval_of_classes: true
  require_admin_approval_of_blogs: true

  mailer:
    send_from: admin@example.com
    contact_us_at: admin@example.com
    noreply: noreply@example.com

  social_pages: 
    facebook: https://www.facebook.com/duroosi
    twitter: https://twitter.com/duroosi
    google-plus: https://plus.google.com/101434561769243560321
    youtube:
    linkedin:
    github:
