<%
  adapter = 'my'
  if Rails.application.secrets.database['adapter'].present? 
    adapter = 'pg' if Rails.application.secrets.database['adapter'].downcase == 'postgresql'
  end

  database = Rails.application.secrets.database['name']
%>

default_my: &default_my
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= Rails.application.secrets.database["username"] %>
  password: <%= Rails.application.secrets.database["password"] %>
  socket:   <%= Rails.application.secrets.database["socket"] %>

default_pg: &default_pg
  adapter: postgresql
  encoding: unicode

development:
  <<: *default_<%= adapter %>
  database: <%= database %>_development

test:
  <<: *default_<%= adapter %>
  database: <%= database %>_test

production:
  <<: *default_<%= adapter %>
  database: <%= database %>
  pool: 25

  