# Be sure to restart your server when you modify this file.

common: &common
  site:
    su_name: <%= ENV["SU_NAME"] || 'Super User' %>
    su_email: <%= ENV["SU_EMAIL"] || 'admin@example.com' %>
    su_password: <%= ENV["SU_PASSWORD"] || 'secretive' %>

  database:
    adapter: postgresql # mysql or postgresql
    name: duroosi
    username: <%= ENV["DATABASE_USERNAME"] || ENV["USER"] %>
    password: <%= ENV["DATABASE_PASSWORD"] || 'secretive' %>
    socket: <%= RUBY_PLATFORM.downcase.include?("darwin") ? '/tmp/mysql.sock' : '/var/run/mysqld/mysqld.sock' %>

  storage:
    type: file
    asset_host: 'http://localhost:3000'

    # Needed only if you're planning to use Amazon AWS fot file upload
    fog:
      directory: <%= ENV["AWS_DIRECTORY"] %>
      public: true
      aws:
        access-key-id: <%= ENV["AWS_KEY_ID"] %>
        secret-access-key: <%= ENV["AWS_ACCESS_KEY"] %>
        region: <%= ENV["AWS_REGION"] %>

  auth_mailer_sender: <%= ENV["SU_EMAIL"] %>
  auth: 
    facebook:
      id: <%= ENV["AUTH_FACEBOOK_ID"] %>
      secret: <%= ENV["AUTH_FACEBOOK_SECRET"] %>
    google:
      id: <%= ENV["AUTH_GOOGLE_ID"] %>
      secret: <%= ENV["AUTH_GOOGLE_SECRET"] %>

development:
  <<: *common
  
  # Your secret key is used for verifying the integrity of signed cookies.
  secret_key_base: e0fa05385ec9e9a58b818ec08e01c666d1368f94de9f26dc6c28836f586b7c1d382876a713468be38ff4c4a8aae0aa0a0d35911b89d208cc0f6fd236829e80c1

  mailer:
    host: ENV["MAILER_HOST"]
    port: 587
    domain: ENV["MAILER_DOMAIN"]
    username: ENV["MAILER_USERNAME"]
    password: ENV["MAILER_PASSWORD"]

test:
  <<: *common
  secret_key_base: fb1092c55e5c05931fb3d618a2e489c0cfa6ff27f748a7f1318504021f7eb7e374d49f178c5ea9636f0aee27fe3eb958839395accb63fa6b45193711441f13aa

# Do not keep production secrets in the repository
production:
  <<: *common

  # Your secret key is used for verifying the integrity of signed cookies.
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  mailer:
    host: ENV["MAILER_HOST"]
    port: 587
    domain: ENV["MAILER_DOMAIN"]
    username: ENV["MAILER_USERNAME"]
    password: ENV["MAILER_PASSWORD"]
