# Be sure to restart your server when you modify this file.

common: &common
  site:
    su_name: Super User
    su_email: admin@example.com
    su_password: a_secret

  database:
    adapter: postgresql # mysql or postgresql
    name: curriculr
    username: db_user
    password: secret
    socket: <%= RUBY_PLATFORM.downcase.include?("darwin") ? '/tmp/mysql.sock' : '/var/run/mysqld/mysqld.sock' %>

  redis_enabled: true

  storage:
    type: file
    asset_host: 'http://localhost:3000'

    # Needed only if you're planning to use Amazon AWS fot file upload
    fog:
      directory: curriculr
      public: true
      AWS:
        aws_access_key_id: xxx                 # required
        aws_secret_access_key: yyy             # required
        region: eu-west-1                      # optional, defaults to 'us-east-1'
        host: s3.example.com                   # optional, defaults to nil
        endpoint: https://s3.example.com:8080  # optional, defaults to nil

      # Rackspace:
      #   rackspace_username: xxx
      #   rackspace_api_key: yyy
      #   rackspace_region: ord

      # Google:
      #   google_storage_access_key_id: xxx
      #   google_storage_secret_access_key: yyy
  
  auth: 
    facebook:
      id: xxx
      secret: yyy
    google_oauth2:
      id: xxx
      secret: yyy

development:
  <<: *common
  
  # Your secret key is used for verifying the integrity of signed cookies.
  secret_key_base: e0fa05385ec9e9a58b818ec08e01c666d1368f94de9f26dc6c28836f586b7c1d382876a713468be38ff4c4a8aae0aa0a0d35911b89d208cc0f6fd236829e80c1

  mailer:
    host: mail.example.com
    port: 587
    domain: example.com
    username: user
    password: secret

test:
  <<: *common
  redis_enabled: false
  secret_key_base: fb1092c55e5c05931fb3d618a2e489c0cfa6ff27f748a7f1318504021f7eb7e374d49f178c5ea9636f0aee27fe3eb958839395accb63fa6b45193711441f13aa

# Do not keep production secrets in the repository
production:
  <<: *common

  # Your secret key is used for verifying the integrity of signed cookies.
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  mailer:
    host: ENV["MAILER_HOST"]
    port: 587
    domain: ENV["MAILER_DOMAIN"]
    username: ENV["MAILER_USERNAME"]
    password: ENV["MAILER_PASSWORD"]
